incorporate spec changes
open-component-model/ocm-spec pull request #56
Opened 2023-05-05 13:17 UTC by mandelsoft

- new access method for helm repositories
- component descriptor normalization according to RFC8785 (JCS)
- version mapping for mapping OCM versions to OCI tags.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature user

```

2023-06-02 07:33 UTC, jensh007 requested changes

2023-06-02 07:33 UTC, jensh007 commented on doc/appendix/E/README.md
> +format. But specific access methods, e.g. the [`ociArticat`](../B/ociArtifact.md)
There is still a typo in the link.

2023-06-02 07:33 UTC, jensh007 commented on doc/glossary.md
> +An set of files describing the deplyoment of a Kubernetes application using
Typo: A set

2023-06-02 07:33 UTC, jensh007 commented on doc/specification/formats/componentdescriptor_normalization.md
> +  There are to such normalizations:
type: Two

2023-06-02 07:33 UTC, jensh007 commented on doc/specification/formats/componentdescriptor_normalization.md
> +  serialize the resulting JSON object.
typo: serializing

2023-06-02 07:33 UTC, jensh007 commented on doc/specification/formats/componentdescriptor_normalization.md
> +
Suggestion: A component descriptor contains static information and information which may change (for example the access methods specifications usually will be changed during a transport step. A digest should be stable even after transport and therefore should only hash static information.

2023-06-02 07:33 UTC, jensh007 commented on doc/specification/formats/componentdescriptor_normalization.md
> +property `signing` not to be removed and thus be part of the signature.
Labels are removed before signing but can be marked with a special boolean property `signing`. This property indicates that the label should be part of the digest.

2023-06-02 07:33 UTC, jensh007 commented on doc/specification/formats/componentdescriptor_normalization.md
> +The label values is takes as it is, preserving a potentially deep structure.
signature --> digest
typo: taken
deep --> deeply nested

2023-06-02 07:33 UTC, jensh007 commented on doc/specification/formats/componentdescriptor_normalization.md
> +
Normalization

2023-06-02 07:33 UTC, jensh007 commented on doc/specification/formats/componentdescriptor_normalization.md
> +If a resource should not be part of the normalisation and later signing, the resource needs a special digest in the following format:
normalization

2023-06-02 07:33 UTC, jensh007 commented on doc/specification/formats/componentdescriptor_normalization.md
> +  normalisationAlgorithm: EXCLUDE-FROM-SIGNATURE
normalizationAlgorithm

2023-06-02 07:33 UTC, jensh007 commented on doc/specification/formats/normalization.md
> +to an immutable technical reprsentation containing only signature relevant information. This process is called [*component descriptor normalization*](componentdescriptor_normalization.md).
representation

2023-06-12 09:11 UTC, mandelsoft commented on doc/specification/formats/componentdescriptor_normalization.md
> +  normalisationAlgorithm: EXCLUDE-FROM-SIGNATURE
Ha, unfortunaltely this is pat of the interface, which cannot be easily changed. I asked for this right after it has been introduced, but there were already lots of CV.

2023-06-12 10:47 UTC, jensh007 approved these changes

2023-06-12 10:47 UTC, merged