Better readability of OCM spec
open-component-model/ocm-spec pull request #89
Opened 2023-10-12 12:31 UTC by jensh007

**What this PR does / why we need it**:
Major parts rewritten new structure proposed

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature user

```

2023-10-12 15:01 UTC, mandelsoft requested changes

2023-10-12 15:01 UTC, mandelsoft commented on README.md
> +The _Open Component Model (OCM)_ is an open standard to describe software-bill-of-deliveries (SBOD). OCM is a technology-agnostic and machine-readable format focused on the software artifacts that mu
*OCM provides a globally unique identity scheme* `which can be used to identify components ad artifacts`  *throughout the entire software lifecycle management process,....*
`Its focus is to describe versioned sets of artifacts and and to assign globally unique identities.` *OCM makes software those artifacts queriable: what is inside, where is it from, is it authentic etc.*  `But is does not deal with building those artifacts or how to deploy them, Those and other tasks are left to tools  working on-top of the software description model. being able to access the artifact content by its identify. Different tools may keep their own meta data bound together by the identities provided by the model. This way OCM provides a common language usable to all tools to talk about software artifacts, regardless of the technologies and the processes working on them.
Tool specific meta data, like deployment descriptions are handled as own (appropriately typed) artifacts.
This enabled the provisioning of content agnostic tools, for example, for transporting software from one environment into another, signing and verification, providing compliance data, etc.`
`

Such key features should be described here, especially because they are required to understand the diagram.

2023-10-12 15:01 UTC, mandelsoft commented on README.md
> +* 1.[Model](docs/01-model/README.md)
I'm missing a clear separation between model specification and extension here.

The model consists of three parts:
- The model elements
  -  The overall structure:  components, versions (as artifact sets) and repositories to persist model elements
  -  The elements used to describe a component version
- Core processes defined on the model elements
  - Basic signing procedure
- The specification of the extension points and how they interact with the model
   - OCM Repositories  used to host component versions
     - The basic operations for persisting the elements of the model.
   - Access methods for accessing artifact content
   - Artifact types
   - Normalization used to distinguish signing-relevant parts from volatile parts of a component version
   - Digesters/Hashers
   - Signers

Then there could be some processing tools as examples for applications working on the model
- The transport of OCM content
- Howto embed tool specific content
  - tool-specific descriptors
  - relative resource references to build the bridge from descriptors hosted as separate artifact to other
    CV content.

Here I'm not sure how to distinguish between application and model spec. For example, the
relative resource reference format SHOULD be standardized, but does not appear in the model specification, because it is not part of it. May be, we could add it the the Core processes section.

Then there are the already defined *instances* of those extension points.
- the defined repository types and their mappings (CTF, OCI, S3)
- the defined access methods and the descriptor fields
- the defined Digesters
- the defined Signers

2023-10-12 15:01 UTC, mandelsoft commented on doc/01-model/README.md
> +
Here I would add a short introduction of the overall structure of the OCM (and then, may be the structural elements of OCM, like components, versions and repositories). I think, this is partly in 01-model.md, but it should prepare the complete scene.

Software is structured into components, which are abstract elements representing a dedicated meaning or semantic.
Components have versions, which describe sets of artifacts. 

The definition of the naming scheme (the lingua franca). Here the picture with the identity composition could be placed.

Component versions are described by a component descriptor (with your example).

For artifacts the model describes the
- an identify in the component version
- a semantic type
- arbitrary structured additional information
- the technical access access information to gain access to the content of the artifact, which may be stored in any supported repository technology.

The component version meta information is stored in OCM repositories, which may use arbitrary backend technologies, like filesystem, OCI or S3.

2023-10-12 15:01 UTC, mandelsoft commented on doc/01-model/03-example.md
> +    labels:                 # labels on this resource as key-value pairs
May be, the fields should generally be ordered according to their importance.
access:  type (other direct attrs (mediaType, localReference, referenceName). globalAccess

2023-10-12 15:01 UTC, mandelsoft commented on doc/01-model/02-elements.md
> +All those described elements share a common set of metadata.
Components and Version are already introduced in another section, so just remove the section header, this section describes (or should describe) only descriptive  elements of a component version.

2023-10-12 15:01 UTC, mandelsoft commented on doc/01-model/02-elements.md
> +For example, a helm chart (type `helmChart`) can be represented as OCI artifact or helm chart archive. Nevertheless, the technical meaning is the same. In both cases the artifact (resource)`type` wil
.. or even ab blob in an S3 bucket.  (just to use an additional storage not natively supported by helm)

2023-10-12 15:01 UTC, mandelsoft commented on doc/01-model/02-elements.md
> +The access type `ociArtifact` however is also used for container images:
... The access method only describes the technical access to an artifact, but not content type related information. ....

(this was always misunderstood in various conversations I had)

2023-10-12 15:01 UTC, mandelsoft commented on doc/01-model/02-elements.md
> +
I would separate the concrete  instances of types and just bring a simple example. It is not relevant for the understanding, blows up the text, and should not be part of the core spec at all. The instance of extension points should be listed in a separate chapter not part of the versioning scheme of the the core spec.

2023-10-12 15:01 UTC, mandelsoft commented on doc/01-model/02-elements.md
> +A *Component* is technically defined by a globally unique identifier.
Resources, sources and references with their (additional fields) are explained earlier, but they all have such identities.
Therefore, I would state at the beginning, that a CV hosts three kinds of elements, resources, sources and references,
All those elements are identified in the context of a component version by a common element identity.
Then below elements, the first sub chapter should be the explanation of identities, so that subsequent chapter can refer to it.

The next common thing of all such elements are arbitrarily typed labels. But they are also used for other descriptive elements like the CV itself and the provider information.

May be, we should put the important common CV related attributes at the beginning, when talking about CVs.
And here we could introduce the labels and refer to this chapter, here.

2023-10-12 15:01 UTC, mandelsoft commented on doc/01-model/02-elements.md
> +
Here several things are mixed up, the component/version identity and the element identity.

The CV identity should be places at the beginning when motivating the CV .

2023-10-12 15:01 UTC, mandelsoft commented on doc/01-model/02-elements.md
> +  ...
just to remember, we also have predefined extra identity identifiers, which should be described as part of the extension points.

2023-10-12 15:01 UTC, mandelsoft commented on doc/01-model/02-elements.md
> +
duplicate from the access specification section.

2023-10-12 15:01 UTC, mandelsoft commented on doc/01-model/02-elements.md
> +Access to a commit in a Git repository.
The concrete instances of the access spec extension points should be separated into an extensions section.

2023-10-12 15:01 UTC, mandelsoft commented on doc/01-model/05-contract.md
> +# Model Contract
This seems to be relevant for the processing section. It does not contain any model related specification.

2023-10-12 15:01 UTC, mandelsoft commented on doc/01-model/06-conventions.md
>  There are some conventions, which should be applied to provide a uniforms
uniform

2023-10-12 15:01 UTC, mandelsoft commented on doc/01-model/06-conventions.md
> +# Conventions
This seems to be the definition of standard extraIdentity attributes.

Yes, may be it is better to put it into a dedicated conventions section.

But then it should not be part of model section, may be a dedicated section on the same level.

2023-10-12 15:01 UTC, mandelsoft commented on doc/02-processing/01-references.md
> +A component version reference describes only the component version and no location or OCM repository. It is always evaluated in the actual repository context. In this way references are stable across
the restriction to the same repo context should be removed.

2023-10-12 15:01 UTC, mandelsoft commented on doc/02-processing/01-references.md
> +# Referencing
The component references are/should be described as part of the CV-model elements.

2023-10-12 15:01 UTC, mandelsoft commented on doc/02-processing/01-references.md
> +
Relative ArtifactRefs are important, but I'm not shure, where to put it (see my comments somewhere above.

In the model itself, they do not appear. They are important for the embedding of tool specific descriptor artifacts. May be, this could be a good place.

Or we keep it as an explicit section, here. With the focus. How to identify artifacts in a CV graph.
May be, we could it place it somewhere below a model identity scheme section.

2023-10-13 08:01 UTC, morri-son commented
/vote-profileocm

2023-10-13 08:10 UTC, morri-son commented
@mandelsoft can you please directly do the minor changes you proposed above in the branch? I propose to do the changes that are bigger after the merge in the already new(er) structure.

2023-10-13 12:08 UTC, jensh007 commented on README.md
> +The _Open Component Model (OCM)_ is an open standard to describe software-bill-of-deliveries (SBOD). OCM is a technology-agnostic and machine-readable format focused on the software artifacts that mu
This point is valid. But this information does not belong into the very first overview section. This is not introductory information.

2023-10-13 12:11 UTC, jensh007 commented on README.md
> +* 1.[Model](docs/01-model/README.md)
I can not quite follow these arguments. Model elements have their own sections. Without the concrete specification (what you call "extension") the specification is meaningless. This was the initial feedback that the spec is hard to read.

2023-10-13 12:13 UTC, jensh007 commented on doc/01-model/README.md
> +
I am open to extend this.

2023-10-13 12:13 UTC, jensh007 commented on doc/01-model/03-example.md
> +    labels:                 # labels on this resource as key-value pairs
Agreed.

2023-10-13 12:14 UTC, jensh007 commented on doc/01-model/06-conventions.md
>  There are some conventions, which should be applied to provide a uniforms
yes typo.... agree.

2023-10-13 12:17 UTC, jensh007 commented on doc/01-model/06-conventions.md
> +# Conventions
We can rename this. But it must be clear if extraIdentity attributes are standardized in any way or free to use. It makes only sense to move them to another chapter if they are used outside of what is described in model.

2023-10-13 12:18 UTC, jensh007 commented on doc/02-processing/01-references.md
> +A component version reference describes only the component version and no location or OCM repository. It is always evaluated in the actual repository context. In this way references are stable across
unclear to me: is "in the actual repository context" wrong then?

2023-10-13 12:19 UTC, jensh007 commented on doc/02-processing/01-references.md
> +
I struggled with the relative ArtifactRefs as well. We can rethink how to handle them in the spec.

2023-10-13 12:21 UTC, jensh007 commented
> @mandelsoft can you please directly do the minor changes you proposed above in the branch? I propose to do the changes that are bigger after the merge in the already new(er) structure.

I agree, would prefer with merging, then fix the smaller issues and create separate issues for some of them (those needing more discussion).

2023-10-17 07:26 UTC, mandelsoft commented on doc/02-processing/01-references.md
> +A component version reference describes only the component version and no location or OCM repository. It is always evaluated in the actual repository context. In this way references are stable across
yes

2023-10-23 09:17 UTC, jensh007 commented
Closing this after lot of follow-up discussions in favor of #91

2023-10-23 09:17 UTC, closed without merging